# Generated by Django 5.1.2 on 2024-10-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_user_name_alter_newuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
