# Generated by Django 5.1.2 on 2024-11-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='person',
            new_name='owner',
        ),
    ]
