# Generated by Django 5.1.2 on 2024-11-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='postc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
