# Generated by Django 5.1.2 on 2024-11-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comments_postc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com', to='post.post'),
        ),
    ]
